---
- hosts: lamp_www
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - block:
      - name: "Set the the ipv4 public address by https://ipinfo.io/"
        uri:
          url: https://ipinfo.io/ip
          return_content: yes
        register: ipinfo_content
      - name: "Set the IPv4 address as variable"
        set_fact:
          ip_address: "{{ ipinfo_content.content | replace('\n', '') }}"
      - name: "Set the FQDN xio.io"
        set_fact:
          dns_name: "{{ ip_address }}.xip.io"
      delegate_to: "{{ groups['lamp_https'][0] }}"


  roles:
    - geerlingguy.firewall
    - geerlingguy.repo-epel
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached

  tasks:
    - name: "Remove the Apache test page"
      file:
        path: /var/www/html
        state: absent
    - name: "Place /var/www/html"
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
        owner: root
        group: root
    - name: "Download WordPress cli"
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: 0755
    - name: "Download latest WordPress locally"
      command: "/usr/local/bin/wp core download --path=/var/www/html --locale=fr_FR --allow-root"
    - name: "Install mysql client"
      package:
        name: mysql
    - name: WordPress configuration
      command: "/usr/local/bin/wp config create --dbname={{ wp_database_name }} --dbuser={{ wp_database_username }} --dbpass={{ wp_database_password }} --dbhost={{ wp_database_host }} --path=/var/www/html --allow-root"
    - name: Install Wordpress
      command: "/usr/local/bin/wp core install --url={{ wp_site_name }} --title={{ wp_site_title }} --admin_user={{ wp_admin_username }} --admin_password={{ wp_admin_password }} --admin_email={{ wp_admin_email }} --path=/var/www/html --allow-root"
    - name: "Download latest WordPress locally"
      command: "/usr/local/bin/wp update --all --path=/var/www/html"

    - name: Test secure connection to TLS domain.
      uri:
        url: https://{{ dns_name }}/
        status_code: 200
      delegate_to: localhost
      become: false
