---
- include_playbook: playbooks/db/main.yml
- include_playbook: playbooks/memcached/main.yml
- include_playbook: playbooks/varnish/main.yml
- include_playbook: playbooks/https/main.yml
- include_playbook: playbooks/www/main.yml
